import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import * as THREE from 'three';
import { BREAK_REACH } from '../src/tap-influence.js';

const out = 'output/taps';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome', args: ['--mute-audio'] });
const errors = [], checks = [];
let page;
try {
  page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto(process.env.RESTORE_URL || 'http://127.0.0.1:5209/', { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => window.__restoreDiagnostics?.().state.ready, null, { timeout: 60000 });
  const read = () => page.evaluate(() => window.__restoreDiagnostics());
  const advance = ms => page.evaluate(time => window.advanceTime(time), ms);
  const target = data => data.state.objects.find(object => object.id === 'crate-02');
  const crate = data => data.state.crates.find(object => object.id === 'crate-02');
  const tap = async () => {
    const object = target(await read());
    assert.ok(object?.screen.x > 50 && object.screen.x < 1390 && object.screen.y > 50 && object.screen.y < 830, 'crate tap target is outside the visible view');
    await page.mouse.click(object.screen.x, object.screen.y);
    return read();
  };
  const gestureSounds = data => Object.fromEntries(['break', 'pickup', 'drop'].map(type => [type, data.audio.eventCounts[type] || 0]));
  await advance(3000);
  const initial = await read();
  const before = target(initial).position;
  const first = await tap();
  assert.equal(first.input.lastTap?.objectId, 'crate-02');
  assert.equal(first.input.lastTap.kind, 'nudge');
  assert.ok(first.input.lastTap.distance > BREAK_REACH);
  assert.equal(crate(first).state, 'closed');
  assert.equal(first.state.openedCrates, 0);
  assert.deepEqual(gestureSounds(first), gestureSounds(initial), 'a nudge played a break, pickup, or drop sound');
  const firstContact = first.audio.lastEvents.findLast(event => event.type === 'nudge');
  assert.match(firstContact?.clip || '', /repair\/hit-wood-/, 'the nudge did not use wood contact audio');
  await advance(350);
  const nudged = await read();
  const displacement = Math.hypot(...target(nudged).position.map((value, index) => value - before[index]));
  assert.ok(displacement > .001, 'the distant tap did not move its closed crate');
  checks.push('a distant pointer tap nudges its closed crate with wood contact audio and no destruction or grab sounds');
  await page.screenshot({ path: `${out}/nudged.png` });

  await page.keyboard.press('KeyR');
  await page.keyboard.down('KeyS');
  await advance(1800);
  await page.keyboard.up('KeyS');
  await page.waitForTimeout(350);
  const farther = await tap();
  assert.equal(farther.input.lastTap?.objectId, 'crate-02');
  assert.equal(farther.input.lastTap.kind, 'nudge');
  assert.ok(farther.input.lastTap.distance > first.input.lastTap.distance + 2, 'the player did not move farther from the crate');
  assert.ok(farther.input.lastTap.strength < first.input.lastTap.strength * .4, 'longer range did not substantially weaken the nudge');
  assert.equal(crate(farther).state, 'closed');
  assert.equal(farther.state.openedCrates, 0);
  checks.push('walking farther away substantially weakens a tap while the crate remains intact');

  await advance(800);
  const distantTarget = target(await read());
  await page.mouse.move(distantTarget.screen.x, distantTarget.screen.y);
  await page.mouse.down();
  await page.waitForFunction(() => window.__restoreDiagnostics().state.grab.objectId === 'crate-02', null, { timeout: 4000 });
  const held = await read();
  assert.equal(held.state.grab.whole, true);
  assert.equal(held.state.grab.kind, 'crate');
  assert.equal(held.state.openedCrates, 0);
  assert.ok(held.input.desktopGrab, 'the long-range hold did not start the normal dragging interaction');
  await page.mouse.up();
  checks.push('holding at long range still picks up an intact crate normally');

  await page.keyboard.press('KeyR');
  let current = await read();
  const camera = new THREE.PerspectiveCamera(current.input.camera.fov, current.input.camera.aspect, .05, 260);
  camera.position.fromArray(current.input.camera.position);
  camera.quaternion.fromArray(current.input.camera.quaternion);
  camera.updateMatrixWorld(true);
  const destination = new THREE.Vector3(0, 0, 2.2).project(camera);
  await page.keyboard.down('Shift');
  await page.mouse.click((destination.x * .5 + .5) * 1440, (-destination.y * .5 + .5) * 900);
  await page.keyboard.up('Shift');
  await page.keyboard.press('KeyQ');
  current = await read();
  assert.equal(current.state.locomotion.teleportCount, 1, 'the player did not teleport closer');
  assert.equal(current.state.openedCrates, 0, 'navigation accidentally broke a crate');
  const nearby = await tap();
  assert.equal(nearby.input.lastTap?.objectId, 'crate-02');
  assert.equal(nearby.input.lastTap.kind, 'break');
  assert.ok(nearby.input.lastTap.distance <= BREAK_REACH);
  assert.equal(crate(nearby).state, 'open');
  assert.equal(nearby.state.openedCrates, 1);
  assert.equal(nearby.state.revealedArtifacts, 1);
  assert.match(nearby.audio.lastEvents.findLast(event => event.type === 'break')?.clip || '', /actions\/timber-break-/);
  checks.push('moving within eight feet lets one real pointer tap break the crate and reveal its artifact');
  await advance(700);
  await page.screenshot({ path: `${out}/nearby-broken.png` });
  assert.deepEqual(errors, []);
  const result = { passed: true, checks, errors, firstTap: first.input.lastTap, fartherTap: farther.input.lastTap, nearbyTap: nearby.input.lastTap, firstDisplacement: displacement };
  await writeFile(`${out}/browser-results.json`, JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} catch (error) {
  await writeFile(`${out}/browser-failure.json`, JSON.stringify({ message: error.message, checks, errors, diagnostics: await page?.evaluate(() => window.__restoreDiagnostics?.()).catch(() => null) }, null, 2));
  await page?.screenshot({ path: `${out}/browser-failure.png` }).catch(() => {});
  throw error;
} finally {
  await browser.close();
}
